CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node=2 --master_port=57446  training_classifier.py \
    --model_name_or_path "/mnt/data/hf_models/t5-base" \
    --data_path "./data/contrastive_set" \
    --bf16 True \
    --output_dir "./metric_learning_models/0213_sample" \
    --run_name 'llm-fingerprint-0213-2-400' \
    --fold 2 \
    --seed 42 \
    --sample_size 400 \
    --num_train_epochs 25 \
    --per_device_train_batch_size 24 \
    --per_device_eval_batch_size 4 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 2000 \
    --save_total_limit 1 \
    --learning_rate 1e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap" \
    # --tf32 True